name: .NET Build & Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9.0 Preview
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.0-preview.1

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dot
