name: Build and Test .NET 9

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.200'

      - name: Display .NET version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore POEPart1-ChatBot/POEPart1-ChatBot.sln

      - name: Build
        run: dotnet build POEPart1-ChatBot/POEPart1-ChatBot.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test POEPart1-ChatBot/POEPart1-ChatBot.sln --no-build --verbosity normal
