name: .NET Build & Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # Replace if you're using .NET 8.0 or 6.0

    - name: Restore dependencies
      run: dotnet restore
      working-directory: POEPart1-ChatBot

    - name: Build project
      run: dotnet build --no-restore
      working-directory: POEPart1-ChatBot
